Multiplication

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])

In [3]:
u.shape[0]

4

In [4]:
v = np.array([1,0,0,2])

In [5]:
v.shape[0]

4

In [6]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [7]:
vector_vector_multiplication (u,v)

np.float64(14.0)

In [8]:
u.dot(v)

np.int64(14)

Matrix-Vector multiplication

So if p has 4 columns, w must have 4 elements to match.

In [9]:
p = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

In [10]:
p.shape

(3, 4)

The number of columns in p should match the number of elements in w

In [11]:
w = np.array([1,0.5,2,1])

In [12]:
w.shape[0]

4

The result vector needs to hold one number per row of the matrix and the matrix has 3 rows, so the result needs to hold 3 numbers.

Now, p.shape gives you (rows, columns), so:

p.shape[0] = number of rows = 3

So np.zeros(p.shape[0]) is simply creating an empty vector of size 3

Which will eventually be filled with your answers [20, 6, 8.5] as the loop runs

In [13]:
def matrix_vector_multiplication (p,w):
    assert p.shape[1] == w.shape[0]

    result = np.zeros(p.shape[0])

    for i in range(p.shape[0]):
        for j in range(p.shape[1]):
            result[i] += p[i][j] * w[j]

    return result

In [14]:
matrix_vector_multiplication (p,w)

array([20. ,  6. ,  8.5])

Note the function below is different

    result[i] = vector_vector_multiplication(p[i], w)

The v_v_m function from above is reused to replace this line of code
   
   for j in range(p.shape[1]):

p[i] extracts the entire row [i] as a vector, then passes it straight into vector_vector_multiplication along with w.

Why
Matrix × Vector = just doing Vector × Vector repeatedly, once per row
    vector_vector_multiplication — reuse the already built function that handles one row × one column
    p[i] — grab one full row from the matrix at a time
    w — the single vector (one column) stays the same every time

In [15]:
def matrix_vector_multiplication (p,w):
    assert p.shape[1] == w.shape[0]

    num_rows=p.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(p[i], w)

    return result

In [16]:
matrix_vector_multiplication (p,w)

array([20. ,  6. ,  8.5])

In [17]:
p.dot(w)

array([20. ,  6. ,  8.5])

Let's get a new matrix for this

Now lets do a matrix_matrix_multiplication

In [18]:
a = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])


In [35]:
def matrix_matrix_multiplication (p,a):
    assert p.shape[1] == a.shape[0]

    result = np.zeros((p.shape[0],a.shape[1]))

    for i in range (a.shape[1]):
        result[:,i] = matrix_vector_multiplication(p, a[:,i])

    return result

In [36]:
matrix_matrix_multiplication (p,a)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
p.shape

(3, 4)

In [23]:
a.shape

(4, 3)

How do I code without using the matrix_vector_m in the formular


In [33]:
def matrix_matrix_multiplication (p,a):
    assert p.shape[1] == a.shape[0]

    result = np.zeros((p.shape[0],a.shape[1])) #double brackets make it a tuple

    for i in range (p.shape[0]):
        for j in range (a.shape[1]):
            result[:,:] += p[:,:] * a[:,:]

    return result

In [34]:
matrix_matrix_multiplication (p,a)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

Confirmining the answer

In [30]:
p.dot(a)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix 

Denoted with letter I (CAPS), Any matrix * I = Matrix

What is it?

Why is it important?

In [42]:
I = np.eye(4)

In [43]:
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
p

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [41]:
p.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [48]:
I.dot(p)

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

Inverse Matrix

We need the Identity matrix for this

In [74]:
ps = p[:, [0,1,2]]
ps

#make it a 3*3 square matrix by taking the first 3 rows 

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [77]:
ps_inv = np.linalg.inv(ps)
ps_inv

#VS inverse

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [79]:
ps_inv.dot(ps)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

Those tiny values like e-17 are essentially zero — they're just floating point rounding errors, which are normal in numerical computing.