In [1]:
import numpy as np

Creating Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 3.4)

array([3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4])

In [6]:
a = np.array([1,2,4,5,10])
a

array([ 1,  2,  4,  5, 10])

In [7]:
a[2]


np.int64(4)

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5, 10])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,10,11) #fills numbers between o and 10

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Multi-dementional arrays

In [19]:
np.zeros((5,3)) #5 rows and 3 columns - it has double brackets

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [23]:
n[0,1] #accessing no. 2

np.int64(2)

In [29]:
n[1] # the entire row

array([4, 5, 6])

In [28]:
n[0,2] = 10 #changing number 3 to 10

In [26]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
#assign the entire row
n[2] = [10,11,12]

In [32]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [10, 11, 12]])

In [35]:
n[:,1] #getting the second column

array([ 2,  5, 11])

In [36]:
#Reassign the last column
n[:,2] = [50,60,70]

In [37]:
n

array([[ 1,  2, 50],
       [ 4,  5, 60],
       [10, 11, 70]])

Randomly generated arrays

In [39]:
np.random.rand(5,2) #5 rows 2 columns - give different numbers everytime you run

array([[0.29481411, 0.84524737],
       [0.63548289, 0.0648386 ],
       [0.14329564, 0.64940277],
       [0.70564233, 0.6451783 ],
       [0.88806156, 0.66749755]])

In [40]:
#fix by setting seed
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [41]:
#getting numbers from the standard normal distribution
np.random.seed(2)
np.random.randn(5,2) #randn n stands for normal

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [43]:
#generating random intergers
np.random.seed(2)
np.random.randint(low=0,high=100,size =(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
a + 10 #adding 10 to each element

array([10, 11, 12, 13, 14])

In [48]:
a * 2

array([0, 2, 4, 6, 8])

In [49]:
#chaining them
10 + (a*2)

array([10, 12, 14, 16, 18])

In [51]:
(10 + (a+2)) ** 2

array([144, 169, 196, 225, 256])

In [52]:
b= (10 + (a+2)) ** 2
a + b

array([144, 170, 198, 228, 260])

Comparison operations

In [54]:
a

array([0, 1, 2, 3, 4])

In [60]:
a >= 2 #bolean 

array([False, False,  True,  True,  True])

a > b

In [59]:
a[a>=2] #which elements of a are greater or equal to 2

array([2, 3, 4])

Summarizing operations

In [62]:
a.min()

np.int64(0)

In [63]:
a.max()

np.int64(4)

In [64]:
b.sum()

np.int64(990)

In [65]:
b.mean()

np.float64(198.0)

In [66]:
b.std()

np.float64(39.6333193159493)

In [67]:
n.sum()

np.int64(213)